export const Permissions = {
    DEFAULT_PERMISSION: 'DEFAULT_PERMISSION',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    BAN_USER: 'BAN_USER',
    CREATE_USER: 'CREATE_USER',
    ALL: 'ALL'
}